sudo: required
services:
  - docker
language: jvm
jdk: openjdk8
env:
  global:
    secure: oS8m13pia8VwJwIbDTdhsf3Cj71MJDz8KQgaNl3IUi4EOIHYO8Tvd6/kmzPyXr+zM3dcS8cSddm8g0oL/P/FTDuoMIZym52bBf/Rpam0greLK4X0E/bm2/oVTGsJH29fx/7buBWJGbdpxJ7p/4xygVhVaGkHJ8AwOGoKaGRZ2eagZOJy/Ezzt62lXE/aadZk9VbaM7OyQH/A3IAPVGF0qK6tu9LAE42DTsSX98Z0zEmo5Rknhx47ry0R2Qf8f5WX2v/EBRXKyfPSjGwyMxSPuqBVOmqpLsl+nINr8DqOZoL48dEe/vjFRsroFxgE4/6vTWQDDpKaIngx2TVZtu3/2t/ONBChrIX296uSs/fUwUfMmuuQRpLfEe3pgV4nd69G6nQhMvNFxWkPVtpOs7w1w8vhjM1RNSP3JdRDbDj2x1FvURpiGek94D3u1Yg5D7QFmhD2kXGovYZ16IJNy7rWu8dZ2F7VKxqDkcwkq5Gqj+niJ90tw4CBPfB7GaXTjvi8+RAOpp7zmiQJKTiu+K/2E8tJzOtL5f4ZVMqOTNYZqG3MaFdw15sGtt93POgmdfVgIzQWWJRgFRnBQAc5ZZPLvAw1bZynIEh1c/P8MsreXwxRatER8XnukgZ9Ug/69yG3IEI3EfJivePUAKJ3kCSjHXTZqzAKUCW9oIVKNqzG8ls=
node_js: lts/*
install: true
addons:
  apt:
    packages:
      - sudo
      - lsof
      - wget
      - bash
      - curl
      - jq
      - unzip
      - docker-ce
      - python-pip
before_install:
  - sudo pip install docker-compose httpie >/dev/null 2>&1
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080 5432 3306 8082 9092 3306
  - sudo service mysql stop
script:
  - stop_any 80 8080 5432 3306 8082 9092 3306
  - ./mvnw -DskipTests >/dev/null
  - ./mvnw -f docker/all/pom.xml -P up
  - ./mvnw
  #
  - bash ./apps/spring-boot-entity-manager-h2-app/target/*.jar &
  - wait_for 8080
  - http :8080/auto message=h2-ololo
  - http :8080/auto | jq '.'
  - stop_any 8080
  - sleep 1s
  #
  - bash ./apps/spring-boot-entity-manager-mysql-app/target/*.jar &
  - wait_for 8080
  - http :8080/manual message=mysql-trololo
  - http :8080/manual | jq '.'
  - stop_any 8080
  - sleep 1s
  #
  - bash ./apps/spring-boot-entity-manager-postgres-app/target/*.jar &
  - wait_for 8080
  - http :8080/auto message=postgres-trololo
  - http :8080/auto | jq '.'
  - stop_any 8080
  - sleep 1s
  #
  - bash ./apps/spring-boot-spring-data-h2-app/target/*.jar &
  - wait_for 8080
  - http :8080/manual message=h2-spring-data-trololo
  - http :8080/manual | jq '.'
  - stop_any 8080
  - sleep 1s
  #
  - bash ./apps/spring-boot-spring-data-mysql-app/target/*.jar &
  - wait_for 8080
  - http :8080/auto message=mysql-spring-data-ololo
  - http :8080/auto | jq '.'
  - stop_any 8080
  - sleep 1s
  #
  - bash ./apps/spring-boot-spring-data-postgres-app/target/*.jar &
  - wait_for 8080
  - http :8080/manual message=postgres-spring-data-ololo
  - http :8080/manual | jq '.'
  - stop_any 8080
  - sleep 1s
cache:
  packages: true
  npm: true
  directories:
    - ~/.m2/
    - ~/.docker/
    - ./node_modules/
    - ~/.npm/
before_deploy:
  - npm i ; npm run gh-pages
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: ./.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
notifications:
  email: false
git:
  depth: false
  quiet: true
