spring:
  application.name: spring-boot-spring-data-h2-app
  output.ansi.enabled: always
  datasource:
    url: jdbc:h2:tcp://127.0.0.1/./target/spring-data-h2
    name: spring-data-h2
    username: spring-data-h2
    password: spring-data-h2
    hikari:
      connection-test-query: 'SELECT 1'
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    #https://my-blog.now.sh/posts/2019/02/23/Method-PgConnection-createClob-is-not-yet-implemented.html
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.github.daggerok: DEBUG
