version: '2.1'
networks:
  jpa-uuid:
    driver: bridge
services:
  h2:
    extends:
      service: h2
      file: ../h2/docker-compose.yaml
  mysql:
    extends:
      service: mysql
      file: ../mysql/docker-compose.yaml
  postgres:
    extends:
      service: postgres
      file: ../postgres/docker-compose.yaml
  docker-compose-maven-plugin-healthcheck-waiting-container:
    image: busybox
    depends_on:
      h2:
        condition: service_healthy
      mysql:
        condition: service_healthy
      postgres:
        condition: service_healthy
